<?php
/**
 * Created by PhpStorm.
 * User: AB-Nexttech
 * Date: 8/23/2019
 * Time: 6:15 PM
 */

?>
{ title: "Islamabad", id: "Islamabad", selectable: true, color: "#2e7f6c" },
{ title: "Rawalpindi", id: "Rawalpindi", color: "#94C600", selectable: true},
{ title: "Chakwal", id: "Chakwal", color: "#FFC000", selectable: true },
{ title: "Lahore", id: "Lahore", color: " #00B0F0", selectable: true },
{ title: "Haripur", id: "Haripur", color: "#8F5201", selectable: true },
{ title: "Sheikhupura", id: "Sheikhupura", color: "#2e7f6c", selectable: true },
{ title: "Attock", id: "Attock", color: "#8F5201", selectable: true },
{ title: "Sialkot", id: "Sialkot", color: "#00B0F0", selectable: true },
{ title: "Toba Tek Singh", id: "TobaTekSingh", color: "#2e7f6c", selectable: true },
{ title: "Faisalabad", id: "Faisalabad", color: "#FFC000", selectable: true },
{ title: "Mandi Bahauddin", id: "MandiBahauddin", color: "#2e7f6c", selectable: true },
{ title: "Narowal", id: "Narowal", color: "#94C600", selectable: true },
{ title: "Mirpur", id: "Mirpur", color: "#94C600", selectable: true },
{ title: "Skardu", id: "Skardu", color: "#94C600", selectable: true },
{ title: "Malakand", id: "Malakand", color: "#94C600", selectable: true },
{ title: "Bagh", id: "Bagh", color: "#94C600", selectable: true },
{ title: "Haveli", id: "Haveli", color: "#94C600", selectable: true },
{ title: "Kotli", id: "Kotli", color: "#94C600", selectable: true },
{ title: "Gujrat", id: "Gujrat", color: "#94C600", selectable: true },
{ title: "Jhelum", id: "Jhelum", color: "#94C600", selectable: true },
{ title: "Hunza-Nagar", id: "HunzaNagar", color: "#94C600", selectable: true },
{ title: "Gujranwala", id: "Gujranwala", color: "#94C600", selectable: true },
{ title: "Bhimber", id: "Bhimber", color: "#94C600", selectable: true },
{ title: "Mardan", id: "Mardan", color: "#94C600", selectable: true },
{ title: "Nowshera", id: "Nowshera", color: "#94C600", selectable: true },
{ title: "Sargodha", id: "Sargodha", color: "#94C600", selectable: true },
{ title: "Hafizabad", id: "Hafizabad", color: "#94C600", selectable: true },
{ title: "Hattian", id: "Hattian", color: "#94C600", selectable: true },
{ title: "Swabi", id: "Swabi", color: "#94C600", selectable: true },
{ title: "Chitral", id: "Chitral", color: "#94C600", selectable: true },
{ title: "Abbottabad", id: "Abbottabad", color: "#94C600", selectable: true },
{ title: "Astor", id: "Astor", color: "#94C600", selectable: true },
{ title: "Karak", id: "Karak", color: "#94C600", selectable: true },
{ title: "Neelum", id: "Neelum", color: "#94C600", selectable: true },
{ title: "Gilgit", id: "Gilgit", color: "#94C600", selectable: true },
{ title: "Mansehra", id: "Mansehra", color: "#94C600", selectable: true },
{ title: "Layyah", id: "Layyah", color: "#94C600", selectable: true },
{ title: "Poonch", id: "Poonch", color: "#94C600", selectable: true },
{ title: "Okara", id: "Okara", color: "#94C600", selectable: true },
{ title: "Charsadda", id: "Charsadda", color: "#94C600", selectable: true },
{ title: "Sahiwal", id: "Sahiwal", color: "#94C600", selectable: true },
{ title: "Muzaffarabad", id: "Muzaffarabad", color: "#94C600", selectable: true },
{ title: "Karachi Central", id: "KarachiCentral", color: "#94C600", selectable: true },
{ title: "Jhang", id: "Jhang", color: "#94C600", selectable: true },
{ title: "Quetta", id: "Quetta", color: "#94C600", selectable: true },
{ title: "Kasur", id: "Kasur", color: "#94C600", selectable: true },
{ title: "Khanewal", id: "Khanewal", color: "#94C600", selectable: true },
{ title: "Bhakkar", id: "Bhakkar", color: "#94C600", selectable: true },
{ title: "Sudhnutti", id: "Sudhnutti", color: "#94C600", selectable: true },
{ title: "Vehari", id: "Vehari", color: "#94C600", selectable: true },
{ title: "Pakpattan", id: "Pakpattan", color: "#00B0F0", selectable: true },
{ title: "Ghizer", id: "Ghizer", color: "#00B0F0", selectable: true },
{ title: "Kech", id: "Kech", color: "#00B0F0", selectable: true },
{ title: "Ghanchi", id: "Ghanchi", color: "#00B0F0", selectable: true },
{ title: "Peshawar", id: "Peshawar", color: "#00B0F0", selectable: true },
{ title: "Bahawalnagar", id: "Bahawalnagar", color: "#00B0F0", selectable: true },
{ title: "Mianwali", id: "Mianwali", color: "#00B0F0", selectable: true },
{ title: "Multan", id: "Multan", color: "#00B0F0", selectable: true },
{ title: "Khushab", id: "Khushab", color: "#00B0F0", selectable: true },
{ title: "Nankana Sahib", id: "NankanaSahib", color: "#00B0F0", selectable: true },
{ title: "Lodhran", id: "Lodhran", color: "#00B0F0", selectable: true },
{ title: "Hyderabad", id: "Hyderabad", color: "#00B0F0", selectable: true },
{ title: "Swat", id: "Swat", color: "#00B0F0", selectable: true },
{ title: "Bannu", id: "Bannu", color: "#00B0F0", selectable: true },
{ title: "Chiniot", id: "Chiniot", color: "#00B0F0", selectable: true },
{ title: "FR Tank", id: "FRTank", color: "#00B0F0", selectable: true },
{ title: "FR Bannu", id: "FRBannu", color: "#00B0F0", selectable: true },
{ title: "Kohat", id: "Kohat", color: "#00B0F0", selectable: true },
{ title: "Tor Ghar", id: "TorGhar", color: "#00B0F0", selectable: true },
{ title: "Killa Saifullah", id: "KillaSaifullah", color: "#00B0F0", selectable: true },
{ title: "Buner", id: "Buner", color: "#00B0F0", selectable: true },
{ title: "Naushehro Feroze", id: "NaushehroFeroze", color: "#00B0F0", selectable: true },
{ title: "Sukkur", id: "Sukkur", color: "#00B0F0", selectable: true },
{ title: "Dera Ismail Khan", id: "DeraIsmailKhan", color: "#00B0F0", selectable: true },
{ title: "Mastung", id: "Mastung", color: "#00B0F0", selectable: true },
{ title: "Kharan", id: "Kharan", color: "#00B0F0", selectable: true },
{ title: "Gwadar", id: "Gwadar", color: "#00B0F0", selectable: true },
{ title: "Lower Dir", id: "LowerDir", color: "#00B0F0", selectable: true },
{ title: "Ziarat", id: "Ziarat", color: "#00B0F0", selectable: true },
{ title: "Dadu", id: "Dadu", color: "#00B0F0", selectable: true },
{ title: "Rahim Yar Khan", id: "RahimYarKhan", color: "#00B0F0", selectable: true },
{ title: "Larkana", id: "Larkana", color: "#00B0F0", selectable: true },
{ title: "Sibi", id: "Sibi", color: "#00B0F0", selectable: true },
{ title: "Bahawalpur", id: "Bahawalpur", color: "#00B0F0", selectable: true },
{ title: "Lakki Marwat", id: "LakkiMarwat", color: "#00B0F0", selectable: true },
{ title: "Orakzai agency", id: "Orakzaiagency", color: "#FFC000", selectable: true },
{ title: "Nushki", id: "Nushki", color: "#FFC000", selectable: true },
{ title: "Muzaffargarh", id: "Muzaffargarh", color: "#FFC000", selectable: true },
{ title: "Ghotki", id: "Ghotki", color: "#FFC000", selectable: true },
{ title: "Shaheed Benazirabad", id: "ShaheedBenazirabad", color: "#FFC000", selectable: true },
{ title: "Tando Allah Yar", id: "TandoAllahYar", color: "#FFC000", selectable: true },
{ title: "Zhob", id: "Zhob", color: "#FFC000", selectable: true },
{ title: "Hangu", id: "Hangu", color: "#FFC000", selectable: true },
{ title: "Sanghar", id: "Sanghar", color: "#FFC000", selectable: true },
{ title: "Diamir", id: "Diamir", color: "#FFC000", selectable: true },
{ title: "Upper Dir", id: "UpperDir", color: "#FFC000", selectable: true },
{ title: "Lasbela", id: "Lasbela", color: "#FFC000", selectable: true },
{ title: "Khairpur", id: "Khairpur", color: "#FFC000", selectable: true },
{ title: "Bajaur agency", id: "Bajauragency", color: "#FFC000", selectable: true },
{ title: "Jhal Magsi", id: "JhalMagsi", color: "#FFC000", selectable: true },
{ title: "Mohmand agency", id: "Mohmandagency", color: "#FFC000", selectable: true },
{ title: "Shikarpur", id: "Shikarpur", color: "#FFC000", selectable: true },
{ title: "Tank", id: "Tank", color: "#FFC000", selectable: true },
{ title: "Khyber agency", id: "Khyberagency", color: "#FFC000", selectable: true },
{ title: "Khuzdar", id: "Khuzdar", color: "#FFC000", selectable: true },
{ title: "Pishin", id: "Pishin", color: "#FFC000", selectable: true },
{ title: "Shangla", id: "Shangla", color: "#FFC000", selectable: true },
{ title: "Matiari", id: "Matiari", color: "#FFC000", selectable: true },
{ title: "Awaran", id: "Awaran", color: "#FFC000", selectable: true },
{ title: "Jacobabad", id: "Jacobabad", color: "#FFC000", selectable: true },
{ title: "Batagram", id: "Batagram", color: "#FFC000", selectable: true },
{ title: "Tharparkar", id: "Tharparkar", color: "#FFC000", selectable: true },
{ title: "Badin", id: "Badin", color: "#FFC000", selectable: true },
{ title: "Kambar-Shahdadkot", id: "KambarShahdadkot", color: "#FFC000", selectable: true },
{ title: "Panjgur", id: "Panjgur", color: "#FFC000", selectable: true },
{ title: "FR Peshawar", id: "FRPeshawar", color: "#FFC000", selectable: true },
{ title: "Kashmore", id: "KashmoreKandhkot", color: "#FFC000", selectable: true },
{ title: "Jaffarabad", id: "Jaffarabad", color: "#FFC000", selectable: true },
{ title: "Mirpurkhas", id: "Mirpurkhas", color: "#8F5201", selectable: true },
{ title: "Kalat", id: "Kalat", color: "#8F5201", selectable: true },
{ title: "Dera Ghazi Khan", id: "DeraGhaziKhan", color: "#8F5201", selectable: true },
{ title: "Sherani", id: "Sherani", color: "#8F5201", selectable: true },
{ title: "Tando Muhammad Khan", id: "TandoMuhammadKhan", color: "#8F5201", selectable: true },
{ title: "Rajanpur", id: "Rajanpur", color: "#8F5201", selectable: true },
{ title: "Umerkot", id: "Umerkot", color: "#8F5201", selectable: true },
{ title: "Jamshoro", id: "Jamshoro", color: "#8F5201", selectable: true },
{ title: "FR DI Khan", id: "FRDIKhan", color: "#8F5201", selectable: true },
{ title: "Barkhan", id: "Barkhan", color: "#8F5201", selectable: true },
{ title: "Chaghi", id: "Chaghi", color: "#8F5201", selectable: true },
{ title: "Loralai", id: "Loralai", color: "#8F5201", selectable: true },
{ title: "Thatta", id: "Thatta", color: "#8F5201", selectable: true },
{ title: "FR Lakki Marwat", id: "FRLakkiMarwat", color: "#8F5201", selectable: true },
{ title: "Kohistan", id: "Kohistan", color: "#8F5201", selectable: true },
{ title: "Harnai", id: "Harnai", color: "#8F5201", selectable: true },
{ title: "Kachhi", id: "Kachhi", color: "#8F5201", selectable: true },
{ title: "FR Kohat", id: "FRKohat", color: "#E08201", selectable: true },
{ title: "Kurram agency", id: "Kurramagency", color: "#E08201", selectable: true },
{ title: "Nasirabad", id: "Nasirabad", color: "#E08201", selectable: true },
{ title: "Washuk", id: "Washuk", color: "#E08201", selectable: true },
{ title: "Kohlu", id: "Kohlu", color: "#E08201", selectable: true },
{ title: "Sohbatpur", id: "Sohbatpur", color: "#E08201", selectable: true },
{ title: "Musakhail", id: "Musakhail", color: "#E08201", selectable: true },
{ title: "South Waziristan agency", id: "SouthWaziristanagency", color: "#E08201", selectable: true },
{ title: "Dera Bugti", id: "DeraBugti", color: "#E08201", selectable: true },
{ title: "Killa Abdullah", id: "KillaAbdullah", color: "#E08201", selectable: true },
{ title: "North Waziristan agency", id: "NorthWaziristanagency", color: "#E08201", selectable: true },
{ title: "Sujawal", id: "Sujawal", color: "#E08201", selectable: true },
{ title: "Lehri", id: "Lehri", color: "#E08201", selectable: true },
